include: package:pedantic/analysis_options.yaml

analyzer:
  errors:
    avoid_relative_lib_imports: error
    avoid_init_to_null: warning
    avoid_classes_with_only_static_members: warning
    avoid_positional_boolean_parameters: warning
    avoid_returning_null: warning
    avoid_void_async: warning
    avoid_unnecessary_containers: warning
    constant_identifier_names: warning
    empty_catches: warning
    missing_required_param: error
    missing_return: error
    parameter_assignments: warning
    prefer_relative_imports: error
    prefer_single_quotes: error
  exclude:
    - android/app/src/build.gradle
    - '**.g.dart'
    - '/**/*.g.dart'
    - 'lib/**/*.g.dart'
    - '*.yaml'
#
linter:
  rules:
    always_require_non_null_named_parameters: true
    avoid_init_to_null: true
    avoid_classes_with_only_static_members: true
    avoid_private_typedef_functions: true
    avoid_unused_constructor_parameters: true
    avoid_unnecessary_containers: true
    avoid_returning_null: true
    avoid_returning_null_for_future: true
    avoid_returning_null_for_void: true
    avoid_null_checks_in_equality_operators: true
    avoid_relative_lib_imports: true
    avoid_empty_else: true
    avoid_types_as_parameter_names: true
    avoid_types_on_closure_parameters: true
    avoid_return_types_on_setters: true
    avoid_positional_boolean_parameters: true
    avoid_function_literals_in_foreach_calls: true
    annotate_overrides: true
    await_only_futures: true
    avoid_void_async: true
    cancel_subscriptions: true
    camel_case_extensions: true
    camel_case_types: true
    close_sinks: true
    comment_references: true
    control_flow_in_finally: true
    constant_identifier_names: true
    empty_constructor_bodies: true
    empty_statements: true
    empty_catches: true
    file_names: true
    hash_and_equals: true
    missing_return: true
    omit_local_variable_types: false
    no_duplicate_case_values: true
    non_constant_identifier_names: true
    parameter_assignments: true
    prefer_collection_literals: true
    prefer_const_declarations: true
    prefer_contains: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_generic_function_type_aliases: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    prefer_interpolation_to_compose_strings: true
    prefer_if_null_operators: true
    prefer_equal_for_default_values: true
    prefer_conditional_assignment: true
    prefer_initializing_formals: true
    prefer_mixin: true
    prefer_typing_uninitialized_variables: true
    prefer_iterable_whereType: true
    prefer_function_declarations_over_variables: true
    recursive_getters: true
    slash_for_doc_comments: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    sort_unnamed_constructors_first: true
    type_init_formals: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    unnecessary_statements: true
    unnecessary_new: true
    unnecessary_this: true
    unnecessary_const: true
    unnecessary_lambdas: true
    unnecessary_await_in_return: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_null_aware_assignments: true
    use_function_type_syntax_for_parameters: true
    use_to_and_as_if_applicable: true
    use_rethrow_when_possible: true
